on: push

jobs:
  usbotghs-proof:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.release }}
      volumes:
        - /home/runner:/__w/workflow/workflow/build
    strategy:
      fail-fast: false
      matrix:
        release: ["framac/frama-c:21.1", "framac/frama-c:22.0" ] 
    timeout-minutes: 600
    steps:
      - name: checkout workflow
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/workflow
          ref: master
          token: ${{ secrets.FRAMAC_SECRET }} 
          path: build/workflow
      - name: checkout libstd
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/libstd
          ref: incoming
          token: ${{ secrets.FRAMAC_SECRET }} 
          path: build/libstd
      - name: checkout libusbctrl
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/libusbctrl
          ref: incoming
          token: ${{ secrets.framac_secret }} 
          path: build/libusbctrl
      - name: checkout usbotghs
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/driver-stm32f4xx-usbotghs
          ref: incoming
          token: ${{ secrets.framac_secret }} 
          path: build/usbotghs
      - name: Proving usbotghs
        run: |
          apt-get install -y wget unzip
          wget https://github.com/CVC4/CVC4/releases/download/1.7/cvc4-1.7-x86_64-linux-opt
          mv cvc4-1.7-x86_64-linux-opt /usr/bin/cvc4
          chmod +x /usr/bin/cvc4
          wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.6/z3-4.8.6-x64-ubuntu-16.04.zip
          unzip z3-4.8.6-x64-ubuntu-16.04.zip
          mv z3-4.8.6-x64-ubuntu-16.04/bin/z3 /usr/bin
          chmod +x /usr/bin/z3
          why3 config --detect
          why3 --list-provers
          cd build/usbotghs;
          . ../workflow/setenv.usbotghs.sh;
          FRAMAC_TARGET=y make frama-c;
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: framac-results
          path: |
            build/usbotghs/framac/results/*.session
            build/usbotghs/framac/results/*.log

  usbctrl-proof:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.release }}
      volumes:
        - /home/runner:/__w/workflow/workflow/build
    strategy:
      fail-fast: false
      matrix:
        release: ["framac/frama-c:21.1", "framac/frama-c:22.0" ] 
    timeout-minutes: 600
    steps:
      - name: checkout workflow
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/workflow
          ref: master
          token: ${{ secrets.FRAMAC_SECRET }} 
          path: build/workflow
      - name: checkout libstd
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/libstd
          ref: incoming
          token: ${{ secrets.FRAMAC_SECRET }} 
          path: build/libstd
      - name: checkout libusbctrl
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/libusbctrl
          ref: incoming
          token: ${{ secrets.framac_secret }} 
          path: build/libusbctrl
      - name: checkout usbotghs
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/driver-stm32f4xx-usbotghs
          ref: incoming
          token: ${{ secrets.framac_secret }} 
          path: build/usbotghs
      - name: Proving libusbctrl
        run: |
          cd build/libusbctrl;
          . ../workflow/setenv.libusbctrl.sh;
          FRAMAC_TARGET=y make frama-c;
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: framac-results
          path: |
            build/libusbctrl/framac/results/*.session
            build/libusbctrl/framac/results/*.log
