on: push

jobs:
  framac22:
    runs-on: ubuntu-latest
    steps:
      - name: FramaC
        run: |
          sudo apt install opam why3;
          opam init;
          opam install depext;
          opam depext frama-c;
          opam install frama-c;
          why3 config --detect
      - name: checkout libstd
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/libstd
          ref: master
          repo-token:  ${{ secrets.ACCESS_TOKEN }} 
          path: libstd
