on: push

jobs:
  framac22:
    runs-on: framac/fama-c:22.0
    steps:
      - name: checkout libstd
        uses: actions/checkout@v2
        with:
          repository: wookey-sdk/libstd
          ref: master
          repo-token:  ${{ secrets.ACCESS_TOKEN }} 
          path: libstd
